### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by mihilt** [Kyounghwan01/blog#55]
[React18의 새로운 기능 flushsync](https://kyounghwan01.github.io/blog/React/React18/flushsync/)
- [ ] 생긱는 → 생기는

[presentational & container 디자인 패턴](https://kyounghwan01.github.io/blog/React/container-presenter-dessign-pattern/)
- [ ]  않도 → 않아도

**Comment by Kyounghwan01** [comment]
@mihilt 감사합니다!!
