### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by mihilt** [Kyounghwan01/blog#57]
[react-query](https://kyounghwan01.github.io/blog/React/react-query/basic/#usequery-%E1%84%83%E1%85%A9%E1%86%BC%E1%84%80%E1%85%B5%E1%84%8C%E1%85%A5%E1%86%A8%E1%84%8B%E1%85%B3%E1%84%85%E1%85%A9-%E1%84%89%E1%85%B5%E1%86%AF%E1%84%92%E1%85%A2%E1%86%BC)
- [ ] 실횅 → 실행

제가 일부러 찾는 것은 아닌데, 괜히 문법 나치가 된 것 같네요 ㅠㅠ
그냥 보여서요..

블로그 잘 보고 있습니다~

**Comment by Kyounghwan01** [comment]
@mihilt 아! 아니에요 오히려 감사합니다!!
